version: '3'
services:
  first:
    image: blockchain
    container_name: firstContainer
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    volumes:
      - .:/app
    command: "3100"
  second:
    image: blockchain
    container_name: secondContainer
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: "3200"
    volumes:
      - .:/app
  third:
    image: blockchain
    container_name: thirdContainer
    build:
      context: .
      dockerfile: Dockerfile
    network_mode: host
    command: "3300"
    volumes:
      - .:/app